on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        useConfigFile: true
    - name: Create Tag
      run: |
        git tag ${{ env.fullSemVer }}
        git push origin ${{ env.fullSemVer }}
