on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish TicketLottery.csproj -c Release -p:PublishProfile=FolderProfile

    - name: Archive published output
      run: |
        cd publish
        zip -r ../publish.zip .
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
        
    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        useConfigFile: true

    - name: Set Up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Authenticate With GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Myliak/StreamUtilities.git
        
    - name: Create Tag
      env:
        tag: ${{ env.majoMinorPatch }}
      run: |
        git tag $tag
        git push origin $tag

    - name: Release New Version
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.majorMinorPatch }}
        name: ${{ env.majorMinorPatch }}
        files: publish.zip
        generate_release_notes: true
      
    
