on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
        
    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        useConfigFile: true

    - name: Set Up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Authenticate With GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Myliak/StreamUtilities.git
        
    - name: Create Tag
      env:
        tag: ${{ env.majoMinorPatch }}
      run: |
        git tag $tag
        git push origin $tag

    - name: Release New Version
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.majorMinorPatch }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag}" \
            --generate-notes
    
